# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
from osv import fields,osv


class for_categorias_contenidos(osv.osv):
    """Tabla de Referencia de Categorías de Contenidos"""
    _name = 'for.categorias_contenidos'
    _rec_name = 'categoria_nombre'
    _columns = {
        'codigo': fields.char('Código', size=3, required=True, help='Código de Identificación de la Categoría de Contenidos de la Estructura Curricular del PIS'),
        'categoria_nombre': fields.char('Categoría', size=30, required=True, help='Nombre de la Categoría de Contenidos de la Estructura Curricular del PIS'),
        'categoria_descripcion': fields.text('Descripción', required=True, help='Descripción de la Categoría de Contenidos de la Estructura Curricular del PIS'),
    }
for_categorias_contenidos()

class for_estructura_curricular(osv.osv):
    """Registro Maestro de la Estructura Curricular de los Proyectos Integrales Socialistas"""
    _name = 'for.estructura_curricular'
    _rec_name = 'ec_tema'
    _columns = {
        'proyecto_id': fields.many2one('for.pis.registro_inicial','Proyecto', help='Proyecto formativo al cual se asocia la Estructura Curricular'),
        'ec_tema': fields.char('Tema', size=250, required=True, help='Tema de la Matriz Curricular del PIS'),
        'ec_horas': fields.integer('Horas', required=True, help='Horas asignadas al desarrollo del tema identificado en la Matriz Curricular del PIS'),
        'ec_observaciones': fields.text('Observaciones', required=True, help='Observaciones del tema identificado en la Matriz Curricular del PIS'),
        'ec_problema_resuelve': fields.text('Problema que resuelve', required=True, help='Problema que resuleve el tema identificado en la Matriz Curricular del PIS'),
        'categoria_id': fields.many2one('for.categorias_contenidos','Categoría', help='Categoría de Contenido en cual se ubica el tema identificado en la Matriz Curricular del PIS'),
    }
for_estructura_curricular()

#####################################################################################################################################################################################
#########################################################################################################################################################################################
###############herencia de formacion_pis_base####################################################################################################################################

class for_pis_registro_inicial_extended(osv.osv):
    """Registro Inicial de Proyectos Integrales (de Formación) Socialista"""
    _name = 'for.pis.registro_inicial'
    #_rec_name = 'denominacion_pis'
    _inherit= 'for.pis.registro_inicial'
    _columns = {
        'matriz_curricular_ids': fields.one2many('for.estructura_curricular', 'proyecto_id', 'Matriz Curricular', required=False,help='Temas que conforman la Matriz Curricular del Proyecto'),


    }
for_pis_registro_inicial_extended()
###############herencia de formacion_pis_base####################################################################################################################################
##################################################################################################################################################################################3