# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
{
        "name" : "formacion_2015_indagacion",
        "version" : "0.4",
        "author" : "Joan Espinoza, Francisco Vielma",
        "website" : "http://www.inces.gob.ve",
        "category" : "Formacion",
        "description": """  Módulo de Gestión de los Procesos de Indagación de Contexto de los PIS INCES  """,
        "depends" : ['base','formacion_2015_base'],
        "init_xml" : [  'data/for.pis.categorias_discapacidades.csv', 
                        'data/for.pis.condiciones_laborales.csv',
                        'data/for.pis.deportes.csv',
                        'data/for.pis.estados_civiles.csv',
                        'data/for.pis.estatus_niveles_educativos.csv', 
                        'data/for.pis.frecuencias_participacion.csv',
                        'data/for.pis.generos.csv', 
                        'data/for.pis.misiones.csv',
                        'data/for.pis.nacionalidades.csv',
                        'data/for.pis.niveles_academicos.csv', 
                        'data/for.pis.parentescos.csv', 
                        'data/for.pis.pueblos_indigenas.csv',
                        'data/for.pis.rangos_edades.csv', 
                        'data/for.pis.tipos_comunidades.csv', 
                        'data/for.pis.tipos_redes_sociales.csv',  
                        'data/for.pis.tecnologias_tic.csv',
                        'data/for.pis.actividades_culturales.csv',
                        'data/for.pis.areas_conocimientos.csv',
                        'data/for.pis.carreras_universitarias.csv',
                        'data/for.pis.especialidades.csv',
                        'data/for.pis.oficios.csv',
                        'data/for.pis.profesiones_ocupaciones.csv'],
        "demo_xml" : [ ],
        "update_xml" : ['formacion_pis_indagacion_view.xml', 'security/ir.model.access.csv'],
        "installable": True
}
