# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the OpenERP plugin for Dia !
{
        "name" : "formacion_2015_indagacion_espacios",
        "version" : "0.2",
        "author" : "Joan Espinoza, Francisco Vielma",
        "website" : "http://www.inces.gob.ve",
        "category" : "Formacion",
        "description": """  Funcionalidades para Caracterización de Espacios Integrales Socialistas, del Módulo de Gestión de los Procesos de Indagación de Contexto de los PIS INCES  """,
        "depends" : ['base','formacion_2015_base'],
        "init_xml" : ['data/for.pis.criterios_equilibrio_ambiental.csv',
                        'data/for.pis.criterios_seguridad_laboral.csv', 
                        'data/for.pis.turnos.csv',
			'data/for.pis.niveles_innovacion_tecnologica.csv', 
                        'data/for.pis.tipos_contextos.csv',
                        'formacion_pis_indagacion_espacios_view.xml', 
                        'security/ir.model.access.csv',
                        'data/for.pis.tipos_espacios.xml'],
        "demo_xml" : [ ],
        "update_xml" : [],
        "installable": True
}
